### ISSUE TITLE
Add data access notice

### ISSUE THREAD

**Issue by apdavison** [appukuttan-shailesh/cscs_viewer#1]
Before allowing people to download data, they need to be presented with the EBRAINS KG terms of service and data citation requirements, i.e. the text that appears when clicking "Download dataset" on a dataset in the [KG Search](https://kg.ebrains.eu/search/?facet_type[0]=Dataset&facet_Dataset_embargoForFilter[0]=Free)

**Comment by appukuttan-shailesh** [comment]
@apdavison: A few questions on how best to implement this. I was thinking of implementing this as a pop-up, with **accept** and **reject** buttons. If "accept", they can proceed with the download. I was wondering what might be the best way to show this disclaimer:

1) each time the user clicks on download.... might be a bit excessive?
2) the first time the page loads. If they click "**accept**", the download buttons are provided on the page, else not.
3) the first time any item is being downloaded on that page (show until first "**accept**") 

Another query I had was whether every item in a CSCS container is governed by EBRAINS KG terms of service and data citation requirements?

**Comment by apdavison** [comment]
I think option 3 would be best. I guess you would use a session cookie for this?

I guess non-EBRAINS public containers could also be viewed with this if someone knew the URL, but I don't think we have any way to know which project owns a public container (unless it's somewhere in the CSCS metadata), so to be safe we should assume all containers are governed by the EBRAINS KG terms.

**Comment by appukuttan-shailesh** [comment]
Yes, a session cookie seems appopriate.
I presume I would then also need to have a disclaimer on page loading that cookies are used on this web-page?

**Comment by apdavison** [comment]
I guess so

**Comment by appukuttan-shailesh** [comment]
This should now be complete.

**Comment by apdavison** [comment]
- I think the buttons should be "Accept" / "Cancel"
- Clicking on the filename rather than the download button doesn't trigger the dialog

**Comment by appukuttan-shailesh** [comment]
Both done.
